### ISSUE TITLE
update rest-client dependency

### ISSUE THREAD

**Issue by exeral** [sensu-plugins/sensu-plugins-elasticsearch#102]
Hi,

I'm getting troubles while trying install this plugin with other plugins (like sensu-plugins-http)

This plugin has a strict dependency on rest-client = 1.8.0 which is a 2 years old outdated version.
Maybe we could bump the rest-client version dependency ?
I don't know if rest-client has breaking changes for this plugin...

thanks

**Comment by msmith-hpe** [comment]
This is even more annoying now that sensu-go has the ruby 2.4.0 runtime asset available for use and rest-client < 2.0.1 has this issue with ruby 2.4.0: https://github.com/rest-client/rest-client/issues/612

**Comment by phumpal** [comment]
Although I should be I am not familiar with sensu-go. Is the requirement 2.4.0 or 2.4.9? 2.4.x will be EOL on [2020.3.31](https://www.ruby-lang.org/en/downloads/branches/) which could pose a problem.

Are there plans to support 2.5.x mentioned anywhere?

**Comment by majormoses** [comment]
> Are there plans to support 2.5.x mentioned anywhere?

in the context of `sensu-go` I believe sensu inc will maintain the asset of ruby, the maintenance of the plugins themselves follow: https://docs.sensu.io/plugins/latest/faq/#what-is-the-policy-on-supporting-end-of-life-eol-ruby-versions

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/4.1.0

**Comment by phumpal** [comment]
:+1: thank you!
