### ISSUE TITLE
metrics-es-cluster throws undefined method for JSON.parse in 4.0.0 release

### ISSUE THREAD

**Issue by randeffects** [sensu-plugins/sensu-plugins-elasticsearch#148]
Upgrading to 4.0.0 , I get the following error in the `metrics-es-cluster` check:
```"Check failed to run: undefined method `parse' for Sensu::Plugin::Metric::CLI::JSON:Class, [\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-elasticsearch-4.0.0/bin/metrics-es-cluster.rb:125:in `get_es_resource'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-elasticsearch-4.0.0/bin/metrics-es-cluster.rb:98:in `acquire_es_version'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-elasticsearch-4.0.0/bin/metrics-es-cluster.rb:133:in `master?'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-elasticsearch-4.0.0/bin/metrics-es-cluster.rb:201:in `run'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'\"]```
If I rollback to 3.0.0 it works just fine. Sensu version is 1.4.2

**Comment by jspaleta** [comment]
releasing 4.0.1 now with a fix for this. Please re-test with 4.0.1 when you can and close if it's working for you.

**Comment by rwky** [comment]
Works for me!

**Comment by alexhogberg** [comment]
Worked perfectly for me as well, cheers!

**Comment by randeffects** [comment]
Working for me again. Thanks!
