### ISSUE TITLE
Custom @timestamp field

### ISSUE THREAD

**Issue by fatihcode** [sensu-plugins/sensu-plugins-elasticsearch#21]
Hi All,

It would be nice if we could pass custom `@timestamp` (https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/lib/sensu-plugins-elasticsearch/elasticsearch-query.rb#L83) field name via arg. We are using a different timestamp field so it doesn't work for us. :/

For example: `check-es-query-count.rb -h elasticsearch.service.consul -d 'logging-%Y.%m.%d' --timestamp-field field_name`

Thanks

**Comment by cmfatih** [comment]
( cc @eheydrick )

**Comment by eheydrick** [comment]
That'd be a nice improvement. I'd take a PR for making the field configurable.

**Comment by eheydrick** [comment]
Custom `@timestamp` field added with https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/32 and released in 0.5.3.
