### ISSUE TITLE
Unavailable cluster and node statistics

### ISSUE THREAD

**Issue by multani** [sensu-plugins/sensu-plugins-elasticsearch#25]
I'm trying to upgrade my plugin to 0.4.0 and I face the following problem:

* [``metrics-es-cluster`` now tries to collect the ``filter_cache`` metrics](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/commit/918907cba4ace7caab0fd05a57b5495a2d4c83fe#diff-f203641ef617e749f625475f3f1d489eR136) but for some reasons, although it is documented in Elasticsearch documentation, [it is not available on my clusters](https://github.com/elastic/elasticsearch/issues/16226), hence the plugin fails with:
```
Check failed to run: undefined method `[]' for nil:NilClass, [
"/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-elasticsearch-0.4.0/bin/metrics-es-cluster.rb:136:in `acquire_cluster_metrics'",
"/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-elasticsearch-0.4.0/bin/metrics-es-cluster.rb:157:in `run'",
"/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"
]
```

* Same kind of problem happens with the [``metrics-es-node-graphite`` which tries to collect CPU usage](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/commit/24bb8d337819b7af9d8f02e3ffbe1f91287755b3). It is also not available here and [apparently not documented in Elasticsearch documentation?](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#os-stats)

I'm running Elasticsearch 2.1, with ``cloud-aws`` as the only enabled plugin.

**Comment by multani** [comment]
So apparently [``filter_cache`` has been renamed in 2.0.0](https://github.com/elastic/elasticsearch/issues/16226) hence this Sensu handler will not work with these Elasticsearch versions and above.
I'm not sure about the CPU thing though, any opinion? /ping @ChelseaLura

**Comment by eheydrick** [comment]
Thanks for the report @multani. We'll get this fixed up for the metrics in 2.x.

**Comment by ChelseaLura** [comment]
Thanks for pointing this out. :)
Should be fixed, with backwards compatibility, in release 0.4.1. The details of the fix can be found in this [PR](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/27)

**Comment by multani** [comment]
Thanks for the quick fix @ChelseaLura!
