### ISSUE TITLE
check_es_heap.rb tries to assign node from stats before stats is defined

### ISSUE THREAD

**Issue by ajoas** [sensu-plugins/sensu-plugins-elasticsearch#30]
Example error:

outputCheck failed to run: undefined local variable or method `stats' for #<ESHeap:0x00000002d39c60>, ["/etc/sensu/plugins/check-es-heap.rb:110:in `acquire_heap_data'", "/etc/sensu/plugins/check-es-heap.rb:140:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"] 

=====
relevant code:
=====
  def acquire_heap_data(return_max = false)
    node = stats['nodes'].keys.first
    stats = if Gem::Version.new(acquire_es_version) >= Gem::Version.new('1.0.0')
              acquire_es_resource('/_nodes/_local/stats?jvm=true')
            else
              acquire_es_resource('/_cluster/nodes/_local/stats?jvm=true')
            end

**Comment by eheydrick** [comment]
Fixed with #31
