### ISSUE TITLE
elasticsearch gem v 1.0.18 conflicts with 1.0.14

### ISSUE THREAD

**Issue by z-matth** [sensu-plugins/sensu-plugins-elasticsearch#42]
running 

`/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/sensu-plugins-elasticsearch/bin/check-es-cluster-health.rb`

was throwing this error:

> Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
> /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate sensu-plugins-elasticsearch-0.5.3, because elasticsearch-1.0.18 conflicts with elasticsearch (= 1.0.14) (Gem::ConflictError)
> 	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
> 	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:200:in `rescue in try_activate'
> 	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:193:in `try_activate'
> 	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
> 	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
> 	from ./check-es-cluster-health.rb:34:in `<main>'

It seems my system had installed ruby gems 1.0.18  and 1.0.14 by default. To fix this I uninstalled all versions:

`sudo /opt/sensu/embedded/bin/gem uninstall elasticsearch`
`sudo /opt/sensu/embedded/bin/gem uninstall elasticsearch-transport`
`sudo /opt/sensu/embedded/bin/gem uninstall elasticsearch-api`

And then reinstalled the gems specifying version 1.0.14. 

`sudo /opt/sensu/embedded/bin/gem install elasticsearch -v 1.0.14`
`sudo /opt/sensu/embedded/bin/gem install elasticsearch-transport -v 1.0.14`
`sudo /opt/sensu/embedded/bin/gem install elasticsearch-api -v 1.0.14`

Other info on my system:

- Ubuntu 14.04
- Embedded Sensu ruby v = 2.3.0p0
- sensu-client = 0.25.3
- full list of embedded gems and versions below

*** LOCAL GEMS ***

activesupport (4.2.6)
amq-protocol (2.0.1)
amqp (1.6.0)
aws-es-transport (0.1.4)
aws-sdk (2.3.17)
aws-sdk-core (2.3.17)
aws-sdk-resources (2.3.17)
aws-sdk-v1 (1.66.0)
bigdecimal (default: 1.2.8)
childprocess (0.5.8)
chronic_duration (0.10.6)
did_you_mean (1.0.0)
domain_name (0.5.20160615)
elasticsearch (1.0.14)
elasticsearch-api (1.0.14)
elasticsearch-transport (1.0.14)
em-http-server (0.1.8)
em-worker (0.0.2)
eventmachine (1.2.0.1)
faraday (0.9.2)
faraday_middleware (0.10.0)
ffi (1.9.10)
http-cookie (1.0.2)
i18n (0.7.0)
io-console (default: 0.4.5)
ipaddress (0.8.3)
jenkins_api_client (1.4.3)
jmespath (1.2.4)
json (default: 1.8.3)
json_pure (1.8.3)
mime-types (2.99.2)
mini_portile2 (2.1.0, 2.0.0)
minitest (5.8.3)
mixlib-cli (1.6.0)
mixlib-config (2.2.1)
mixlib-log (1.6.0)
mixlib-shellout (2.2.6)
multi_json (1.12.1)
multipart-post (2.0.0)
net-ping (1.7.8)
net-telnet (0.1.1)
netrc (0.11.0)
nokogiri (1.6.8, 1.6.7.2)
numerizer (0.1.1)
ohai (6.16.0)
oj (2.14.6)
pkg-config (1.1.7)
power_assert (0.2.6)
psych (default: 2.0.17)
raindrops (0.16.0)
rake (10.4.2)
rdoc (default: 4.2.1)
redis (3.3.0)
rest-client (1.8.0)
rubygems-update (2.6.4)
sensu (0.25.3)
sensu-extension (1.5.0)
sensu-extensions (1.5.0)
sensu-json (2.0.0)
sensu-logger (1.2.0)
sensu-plugin (1.3.0, 1.2.0)
sensu-plugins-elasticsearch (0.5.3)
sensu-redis (1.4.0)
sensu-settings (5.2.0)
sensu-spawn (2.2.0)
sensu-transport (6.0.0)
socksify (1.7.0)
systemu (2.6.5, 2.5.2)
terminal-table (1.6.0)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
yajl-ruby (1.2.1)`

**Comment by majormoses** [comment]
@z-matth is this from a fresh setup? How are you getting sensu and its sensu gems installed? I am not seeing this in any of my environments. I will try working on replicating but have so far been unable to replicate. It is likely related to this: https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/sensu-plugins-elasticsearch.gemspec#L42 which uses a hard version lock rather than using `~>` I can put togethor a pr for that but might need your help to test as I have yet to replicate.

**Comment by majormoses** [comment]
@z-matth can you try using my fork locally to test? as I can't replicate I cant verify if this would fix your scenario.

**Comment by eheydrick** [comment]
@majormoses's fix will go out in the next release soon.

**Comment by z-matth** [comment]
Verified. Fix works. Thx!
