### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-elasticsearch#47]
I see several enhancements: https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/54a38dddf66919665e2c345812aa712ee6d88a0f/CHANGELOG.md#added  that I feel people would want to have available and constitute a minor version bump. Any chance we could have a release?

**Comment by eheydrick** [comment]
Working on cutting a new release.

**Comment by eheydrick** [comment]
Apart from a few CHANGELOG updates and merging #46 the release is ready to go.

**Comment by majormoses** [comment]
@eheydrick I see everything is merged is there anything else preventing a release?

**Comment by eheydrick** [comment]
Nope, just a matter of finding the time to do it. Aiming to have it out today.

**Comment by majormoses** [comment]
thanks

**Comment by eheydrick** [comment]
1.0.0 is out on rubygems.
