### ISSUE TITLE
Missing ElasticSearch metrics cause formatting issues with metric collection

### ISSUE THREAD

**Issue by TheKevJames** [sensu-plugins/sensu-plugins-elasticsearch#50]
As I mentioned in #49, I'm currently using this plugin to send metrics to Graphite; it's been mostly smooth sailing, but I've been getting a bunch of repeating warnings in my Carbon logs that I think can and should be cleaned up.

Carbon logs:

```
30/09/2016 21:04:10 :: [listener] invalid line (elasticsearch.es_example_net.cluster.fs.disk_reads) received from client 172.16.238.17:54128, ignoring
30/09/2016 21:04:10 :: [listener] invalid line (elasticsearch.es_example_net.cluster.fs.disk_writes) received from client 172.16.238.17:54128, ignoring
30/09/2016 21:04:10 :: [listener] invalid line (elasticsearch.es_example_net.cluster.fs.disk_read_size_in_bytes) received from client 172.16.238.17:54128, ignoring
30/09/2016 21:04:10 :: [listener] invalid line (elasticsearch.es_example_net.cluster.fs.disk_write_size_in_bytes) received from client 172.16.238.17:54128, ignoring
```

Unlike the linked issue, this has to do with _missing values_: the ElasticSearch [health query](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/bin/metrics-es-cluster.rb#L146) used here returns

```
"fs": {
  "total_in_bytes": 102893805568,
  "free_in_bytes": 61906472960,
  "available_in_bytes": 56571641856,
  "spins": "true"
},
```

The [relevant metrics](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/bin/metrics-es-cluster.rb#L151-L154) are not present in this output:

```
$ /opt/sensu/embedded/bin/metrics-es-cluster.rb
# snip
612ab835df79.elasticsearch.cluster.fs.store_in_bytes 0 1475271886
612ab835df79.elasticsearch.cluster.fs.disk_reads
612ab835df79.elasticsearch.cluster.fs.disk_writes
612ab835df79.elasticsearch.cluster.fs.disk_read_size_in_bytes
612ab835df79.elasticsearch.cluster.fs.disk_write_size_in_bytes
612ab835df79.elasticsearch.cluster.fielddata.memory_size_in_bytes 0 1475271886
# snip
```

In the case of missing metrics such as this, it would be great if we could fill in a null default to avoid erroring out Graphite. Perhaps we could set the [output command](https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/bin/metrics-es-cluster.rb#L190) to 

```
output(config[:scheme] + '.' + cluster_metric[0] + '.' + k, v || 0)
```

**Comment by majormoses** [comment]
@TheKevJames would you be willing to put togethor a pr on this for me to review?

**Comment by TheKevJames** [comment]
Sorry this took so long to get around to, see PR #85
