### ISSUE TITLE
Incompatibility with ES 5.0

### ISSUE THREAD

**Issue by captnbp** [sensu-plugins/sensu-plugins-elasticsearch#57]
Hi,

Here are the one which works fine : 
- check-es-indexes.rb
- check-es-cluster-status.rb
- check-es-file-descriptors.rb
- check-es-circuit-breakers.rb
- metrics-es-node.rb

But the others are not yet fixed. I got error 400 issues with (with last gem version sensu-plugins-elasticsearch-1.1.1) : 
- metrics-es-node-graphite.rb
- metrics-es-cluster.rb
- check-es-shard-allocation-status.rb

Ex: `Check failed to run: 400 Bad Request, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `p`

Thanks !

**Comment by fxp0** [comment]
check-es-query-count.rb with option "--minutes-previous" also raise error 400.

**Comment by osigida** [comment]
looks same to https://github.com/sensu-plugins/sensu-plugins-elasticsearch/issues/61
was fixed by https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/60
