### ISSUE TITLE
base64 conversion causes netty exception in elasticsearch client

### ISSUE THREAD

**Issue by msblum** [sensu-plugins/sensu-plugins-elasticsearch#58]
The Base64.encode64 method used in many of these checks will add a newline character to the encoded string if the username:password string is over 60 characters. This doesn't get caught by chomp unless the 61st character happens to be the last one. Credentials encoded in this fashion and sent to authenticate to ES shield then get a "java.lang.IllegalArgumentException: Header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f " error. Using strict conversion with Base64.strict_encode64 would resolve this issue. Issue found for ES 2.3.5

**Comment by majormoses** [comment]
I am supportive of this change, please update your pr as requested.

**Comment by majormoses** [comment]
closed via: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.3.0
