### ISSUE TITLE
metrics-es-node-graphite is responding with 400 on ES 5 

### ISSUE THREAD

**Issue by woqer** [sensu-plugins/sensu-plugins-elasticsearch#61]
Fix: https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/60

**Comment by osigida** [comment]
could we have a release please?

**Comment by nnsaln** [comment]
I still got this issue today

**Comment by osigida** [comment]
@nnsaln sure, we need a release with the fix first

**Comment by eheydrick** [comment]
Working on a new release.

**Comment by eheydrick** [comment]
The ES 5+ fixes are in 1.1.2 now live on rubygems.

**Comment by nnsaln** [comment]
Hi, I still got 
Check failed to run: 400 Bad Request with new  release 1.1.2 rubygems

**Comment by eheydrick** [comment]
@nnsaln Can you try 1.1.3. It has more fixes for ES5.

**Comment by ptqa** [comment]
1.1.2 didn't work for us, but 1.1.3 works fine!
