### ISSUE TITLE
add more url options, host:port does not cover all scenarios

### ISSUE THREAD

**Issue by jpcarey** [sensu-plugins/sensu-plugins-elasticsearch#7]
I'd like to add further url options to allow better flexibility.

An example of something not possible with the current code is to try to check the cluster status of  `http://example.com/elasticsearch`

Looking at elasticsearch curator (https://www.elastic.co/guide/en/elasticsearch/client/curator/current/flags.html), they have broke out the path using the following:

-host
-http_auth
-port
-timeout
-url_prefix
-use_ssl

So, to check the example listed above, it would be the following syntax:
`--host example.com --port 80 --url_prefix elasticsearch`

I wanted to start by discussing this, as 8183cd9ff4bd882e28ae68d84da61f8366449cbe added a --user and --password, which could be compressed to --http_auth user:password

**Comment by mattyjones** [comment]
@jpcarey  I am certainly game to any additional functionally.
