### ISSUE TITLE
Create Grafana Dashboard to visualize metrics

### ISSUE THREAD

**Issue by PatelParas** [sensu-plugins/sensu-plugins-elasticsearch#84]
We have metrics collection scripts:

```
metrics-es-cluster.rb	
metrics-es-node-graphite.rb	
metrics-es-node.rb	
```

It would be great if someone create/share Grafana Dashboard template to fetch data form influxdb or anyother popular timeseries DB.

**Comment by majormoses** [comment]
@PatelParas we try to keep github issues for bugs or enhancements, I would suggest perhaps joining the [community slack](http://sensucommunityslack.herokuapp.com/) or [google group](https://groups.google.com/forum/#!forum/sensu-users) and asking around.

**Comment by mbbroberg** [comment]
Hey @PatelParas, there is definitely a need to think about your dashboarding after data is passed by Sensu. You can ask other members of the Sensu community how they visualize theirs in one of the channels @majormoses shared.
