### ISSUE TITLE
check-es-cluster-status.rb is broken

### ISSUE THREAD

**Issue by rwky** [sensu-plugins/sensu-plugins-elasticsearch#95]
I'm not entirely sure of the intent behind the `--alert-status` flag however it's broken, it will never trigger an alert.

https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/bin/check-es-cluster-status.rb#L148-L154 `options` need replacing with `config` and I imagine the  `!` needs removing and `==` needs replacing with `!=`.

I'm happy to create a PR if the above is correct.

**Comment by driegel** [comment]
I have about 10 machines that check  check-es-cluster-status.rb with version 1.7.0.  The final check result is RED although everything is fine with elasticsearch!!! To me it means, that version 1.7.0 is broken and needs to be fixed quickly! Thanks. 

```
--alert-status STATUS: is not included in the list ['RED', 'YELLOW', 'GREEN'] Usage: /opt/sensu/embedded/bin//check-es-cluster-status.rb (options) --alert-status STATUS Only alert when status matches given (red/yellow) option (or green) (included in ['RED', 'YELLOW', 'GREEN']) -h, --host HOST Elasticsearch host -e, --https Enables HTTPS -m, --master-only Use master Elasticsearch server only -P, --password PASS Elasticsearch Password -p, --port PORT Elasticsearch port -T, --status_timeout SECS Sets the time to wait for the cluster status to be green -t, --timeout SECS Sets the connection timeout for REST client -u, --user USER Elasticsearch User
```

One remark: before I used version 1.2.0 and 1.6.1 ant that versions worked fine.

**Comment by barrebre** [comment]
@rwky If it is broken, please release a PR against it

**Comment by barrebre** [comment]
The intent behind the flag is so that you can send different thresholds to different handlers. For instance, I don't want to be paged on a yellow status but would like to be notified through a message, and visa-versa.

**Comment by rwky** [comment]
Righty-ho now I know the intent I'll create a PR in a bit.

**Comment by majormoses** [comment]
@rwky ping me when you have a PR to review and release. I will yank the gem from rubygems.org.

**Comment by majormoses** [comment]
Yanked: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.7.0

**Comment by rwky** [comment]
PR created it should address the feature @barrebre wants and preserve the old functionality of alerting on all statuses when --alert-status is blank

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.7.1
