### ISSUE TITLE
cluster level heap usage support missing

### ISSUE THREAD

**Issue by cihangirbesiktas** [sensu-plugins/sensu-plugins-elasticsearch#98]
It seems that check-es-heap.rb looks for a single elastic search host's heap usage. Could you add support for the usage of cluster wide heap usage. The check could rise alert when any of the cluster node use heap memory above the threshold.

**Comment by majormoses** [comment]
It could certainly be done, but I don't have the time to work on this but I would be open to reviewing a PR. I'd probably want to move more logic to library functions first to make it a bit easier to refactor.

**Comment by cihangirbesiktas** [comment]
I added support for that and created a PR, could you review?

**Comment by majormoses** [comment]
closed via #99 and released in: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.8.0
